### ISSUE TITLE
-

### ISSUE THREAD

**Issue by dinalbek** [zakkor/rust-sfml-rocket#6]
-

**Comment by dinalbek** [comment]
sfml build error. can you help?

**Comment by zakkor** [comment]
Are you using the install_deps script?
Can you copy paste the error, please?
And what OS are you using?

**Comment by dinalbek** [comment]
i dont have OS i have windows 8.1, not like apple
error git is not recognized as an internal or external command.
and i do 
sudo apt-get install libpthread-stubs0-dev libgl1-mesa-dev libx11-dev libx11-xcb-dev libxcb-image0-dev libxrandr-dev libxcb-randr0-dev libudev-dev libfreetype6-dev libglew-dev libjpeg8-dev libgpgme11-dev libsndfile1-dev libopenal-dev libjpeg62 cmake

and this error is sudo is not recognized as an internal or external command.

pls help.

make script for window, i help

**Comment by dinalbek** [comment]
oh sory os is windows not os apple. i think os is apple os.
